---
title: "Figure 2 (complete)"
output: html_notebook
---

This script will generate a complete version of Figure 2 of our manuscript. It will depict all the 189 scenarios.

```{r}
library(plyr)
library(dplyr)

df_forwarding <- read.csv(file = "../../run/output/marenostrum-4/results/results.csv", sep = ";")
df_gpfs <- read.csv(file = "../../run/output/marenostrum-4-gpfs/results/results.csv", sep = ";")

df <- rbind(df_forwarding, df_gpfs)

str(df)
```

Group the multiple repetitions by scenario and summarize:

```{r}
df_forge_to <- ddply(df, .(forwarders, clients, processes, operation, layout, spatiality, odirect, request, total), summarize,
    N = length(forwarders),

    mean_time = mean(time),
    sd_time = sd(time),
    se_time = 2 * sd_time / sqrt(N),
    median_time = median(time),

    mean_bandwidth = mean(bandwidth),
    sd_bandwidth = sd(bandwidth),
    se_bandwidth = 2 * sd_bandwidth / sqrt(N),
    median_bandwidth = median(bandwidth)
)

df_forge_to$layout_name <- revalue(as.factor(df_forge_to$layout), c(
    "0" = 'file-per-process',
    "1" = 'shared-file'
))

df_forge_to$spatiality_name <- revalue(as.factor(df_forge_to$spatiality), c(
    "0" = 'contiguous',
    "1" = 'strided'
))

str(df_forge_to)
```

Get the number of scenarios and their characteristics:

```{r}
df_selected <- df_forge_to

df_selected$scenario <- paste(sep = '-', df_selected$processes, df_selected$clients, df_selected$layout, df_selected$spatiality, df_selected$request, df_selected$odirect)

unique(df_selected$forwarders)
unique(df_selected$clients)
unique(df_selected$processes)
unique(df_selected$layout)
unique(df_selected$spatiality)
unique(df_selected$request)
unique(df_selected$odirect)

length(unique(df_selected$scenario))
```

Prepare the dataset to plot Figure 2 (complete).

```{r}

df_full <- df

df_full$layout_name <- revalue(as.factor(df_full$layout), c(
    "0" = 'file-per-process',
    "1" = 'shared-file'
))

df_full$spatiality_name <- revalue(as.factor(df_full$spatiality), c(
    "0" = 'contiguous',
    "1" = 'strided'
))

df_full$scenario <- paste(sep = '-', df_full$processes, df_full$clients, df_full$layout, df_full$spatiality, df_full$request, df_full$odirect)
```

Generate Figure 2.

```{r}
library(ggplot2)

plot <- ggplot(df_full[df_full$operation == 'write', ],
    aes(
        x = as.factor(forwarders),
        y = bandwidth
    )) + 
    geom_boxplot() +
    scale_color_manual(
        "",
        values = c(   
            "#796dd5",
            "#6dd5c7",
            "#afd56d",
            "#ef4130",
            "#222222"
        )
    ) +
    facet_wrap(. ~ scenario, scales = "free", ncol = 14) +
    expand_limits(y = 0) +
    ylab("Bandwidth (MB/s)") + 
    xlab("I/O Forwarding nodes") +
    theme_bw() +
    theme(
        legend.position = "top",
        plot.title = element_text(size = 10),
        axis.title.y = element_text(vjust = 0.4), 
        strip.background = element_rect(colour = NA, fill = NA)
    )

pdf(file="../output/figure-2-complete.pdf", width = 25, height = 25)
plot
dev.off()
```

